# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
