# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_lastgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
